In [1]:
from multiprocessing import Pool

import pandas as pd
import numpy as np
from catboost import CatBoost
from catboost import Pool
import lightgbm as lgb

In [2]:
sushi_mst = pd.read_csv("input/sushi3.idata", sep="\t", header=None,
                       names=["item_id", "名前", "スタイル", "大分類", "小分類", "こってり度", "食べる頻度", "正規化した価格", "販売頻度"]).drop("名前", axis=1)
user_mst = pd.read_csv("input/sushi3.udata", sep="\t", header=None,
                       names=["user_id", "性別", "年齢", "回答時間", "長く住んだ県", "長く住んだ地域", "長く住んだ東西",
                              "現在の県", "現在の地域", "現在の東西", "移住"])
pref_melted = pd.read_csv("input/sushi3b.5000.10.score", sep="\s", header=None)

/Users/nobuyuki.ishida/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:6: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [3]:
sushi_mst

    item_id  スタイル  大分類  小分類     こってり度     食べる頻度   正規化した価格  販売頻度
0         0     1    0    6  2.728978  2.138422  1.838420  0.84
1         1     1    0    3  0.926384  1.990228  1.992459  0.88
2         2     1    0    1  1.769559  2.348506  1.874725  0.88
3         3     1    0    5  2.688401  2.043240  1.515152  0.92
4         4     1    0    8  0.813043  1.643478  3.287282  0.88
..      ...   ...  ...  ...       ...       ...       ...   ...
95       95     1    0    2  2.600000  1.094737  1.000000  0.04
96       96     1    0    0  1.970588  1.000000  1.000000  0.04
97       97     1    0    8  1.936709  0.443038  1.500000  0.04
98       98     1    0    0  2.160000  0.613333  1.000000  0.04
99       99     1    0    4  1.779221  0.727273  1.250000  0.04

[100 rows x 8 columns]

In [4]:
user_mst

      user_id  性別  年齢  回答時間  長く住んだ県  長く住んだ地域  長く住んだ東西  現在の県  現在の地域  現在の東西  移住
0        6371   0   2   355       0        0        0     0      0      0   0
1       10007   1   1   214      26        6        1    26      6      1   0
2        1777   1   2   363      29        6        1    26      6      1   1
3        3613   0   4   395      40        9        1    26      6      1   1
4        8081   1   1   707      26        6        1    36      8      1   1
...       ...  ..  ..   ...     ...      ...      ...   ...    ...    ...  ..
4995     5265   0   4   621      31        7        1    13      3      0   1
4996     8756   1   3   316      13        3        0    13      3      0   0
4997     4623   0   1   259      25        6        1    25      6      1   0
4998    10128   1   2   227      21        2        0    14      3      0   1
4999     8637   1   2   300       3        1        0    39      9      1   1

[5000 rows x 11 columns]

In [5]:
pref = pref_melted.stack().reset_index().rename(columns={"level_0": "user_id", "level_1": "item_id", 0: "score"})
pref

        user_id  item_id  score
0             0        0     -1
1             0        1      0
2             0        2     -1
3             0        3      4
4             0        4      2
...         ...      ...    ...
499995     4999       95     -1
499996     4999       96     -1
499997     4999       97     -1
499998     4999       98     -1
499999     4999       99     -1

[500000 rows x 3 columns]

In [6]:
train_df = (
    user_mst.iloc[:4000, :].merge(pref, on="user_id", how="inner").merge(sushi_mst, on="item_id", how="inner")
    .sort_values("user_id")
)
test_df = (
    user_mst.iloc[4000:, :].merge(pref, on="user_id", how="inner").merge(sushi_mst, on="item_id", how="inner")
    .sort_values("user_id")
)
train_df

,user_id,性別,年齢,回答時間,長く住んだ県,長く住んだ地域,長く住んだ東西,現在の県,現在の地域,現在の東西,移住,item_id,score,スタイル,大分類,小分類,こってり度,食べる頻度,正規化した価格,販売頻度
116375,0,0,2,785,26,6,1,8,3,0,1,75,-1,1,0,5,1.581081,1.081081,1.090909,0.08
45075,0,0,2,785,26,6,1,8,3,0,1,29,-1,0,1,11,3.730548,1.456772,1.020000,0.40
128775,0,0,2,785,26,6,1,8,3,0,1,83,-1,1,1,10,2.800000,0.660000,1.000000,0.04
46625,0,0,2,785,26,6,1,8,3,0,1,30,-1,1,0,5,2.331897,1.150862,1.018182,0.40
113275,0,0,2,785,26,6,1,8,3,0,1,73,-1,1,0,0,0.962406,1.624060,1.625000,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66378,4997,0,1,307,9,3,0,9,3,0,0,42,-1,1,0,7,2.246973,0.871671,1.400379,0.24
94278,4997,0,1,307,9,3,0,9,3,0,0,60,0,0,1,11,2.821918,1.214612,1.000000,0.12
112878,4997,0,1,307,9,3,0,9,3,0,0,72,-1,0,0,7,1.869822,1.017751,1.250000,0.08
18328,4997,0,1,307,9,3,0,9,3,0,0,11,4,1,0,2,2.990932,1.700742,2.261244,0.76
22978,4997,0,1,307,9,3,0,9,3,0,0,14,4,1,0,4,2.526978,1.089029,3.646402,0.64

In [7]:
cat_features = range(12)

train_data = train_df.drop(["user_id", "score"], axis=1)
train_label = train_df["score"]
train_group_id = train_df["user_id"]
train_pool = Pool(data=train_data, label=train_label, group_id=train_group_id, cat_features=cat_features)
 
test_data = test_df.drop(["user_id", "score"], axis=1)
test_label = test_df["score"]
test_group_id = test_df["user_id"]
test_pool = Pool(data=test_data, label=test_label, group_id=test_group_id, cat_features=cat_features)
 
# YetiRankはpairwiseでのランク学習の1つ
param = {'loss_function':'YetiRank', 'learning_rate': .05, 'iterations': 200,
         'depth': 4, 'use_best_model':True}
model = CatBoost(param)
model.fit(train_pool, eval_set=test_pool)

Groupwise loss function. OneHotMaxSize set to 10
0:	test: -6.5339073	best: -6.5339073 (0)	total: 218ms	remaining: 43.3s
1:	test: -6.3505383	best: -6.3505383 (1)	total: 381ms	remaining: 37.7s
2:	test: -6.3134098	best: -6.3134098 (2)	total: 547ms	remaining: 35.9s
3:	test: -6.2760068	best: -6.2760068 (3)	total: 703ms	remaining: 34.4s
4:	test: -6.2765069	best: -6.2760068 (3)	total: 860ms	remaining: 33.5s
5:	test: -6.2885137	best: -6.2760068 (3)	total: 1s	remaining: 32.5s
6:	test: -6.2884479	best: -6.2760068 (3)	total: 1.17s	remaining: 32.2s
7:	test: -6.1982258	best: -6.1982258 (7)	total: 1.33s	remaining: 32s
8:	test: -6.1973089	best: -6.1973089 (8)	total: 1.49s	remaining: 31.7s
9:	test: -6.1974759	best: -6.1973089 (8)	total: 1.65s	remaining: 31.4s
10:	test: -6.1974538	best: -6.1973089 (8)	total: 1.82s	remaining: 31.4s
11:	test: -6.0518785	best: -6.0518785 (11)	total: 1.98s	remaining: 31.1s
12:	test: -6.0508650	best: -6.0508650 (12)	total: 2.14s	remaining: 30.8s
13:	test: -6.0414792	best: -6.0414792 (13)	total: 2.31s	remaining: 30.7s
14:	test: -6.0726338	best: -6.0414792 (13)	total: 2.46s	remaining: 30.3s
15:	test: -6.0726379	best: -6.0414792 (13)	total: 2.6s	remaining: 29.9s
16:	test: -6.0726379	best: -6.0414792 (13)	total: 2.75s	remaining: 29.6s
17:	test: -6.0726726	best: -6.0414792 (13)	total: 2.92s	remaining: 29.5s
18:	test: -6.0727958	best: -6.0414792 (13)	total: 3.08s	remaining: 29.4s
19:	test: -6.0556763	best: -6.0414792 (13)	total: 3.24s	remaining: 29.1s
20:	test: -6.0556940	best: -6.0414792 (13)	total: 3.39s	remaining: 28.9s
21:	test: -6.0362760	best: -6.0362760 (21)	total: 3.54s	remaining: 28.7s
22:	test: -6.0361936	best: -6.0361936 (22)	total: 3.7s	remaining: 28.5s
23:	test: -6.0362090	best: -6.0361936 (22)	total: 3.85s	remaining: 28.3s
24:	test: -6.0362225	best: -6.0361936 (22)	total: 4.01s	remaining: 28.1s
25:	test: -5.9584135	best: -5.9584135 (25)	total: 4.18s	remaining: 28s
26:	test: -5.8398252	best: -5.8398252 (26)	total: 4.34s	remaining: 27.8s
27:	test: -5.8394367	best: -5.8394367 (27)	total: 4.5s	remaining: 27.6s
28:	test: -5.8394367	best: -5.8394367 (27)	total: 4.67s	remaining: 27.5s
29:	test: -5.8391614	best: -5.8391614 (29)	total: 4.83s	remaining: 27.4s
30:	test: -5.8391073	best: -5.8391073 (30)	total: 4.99s	remaining: 27.2s
31:	test: -5.8409765	best: -5.8391073 (30)	total: 5.15s	remaining: 27s
32:	test: -5.8412581	best: -5.8391073 (30)	total: 5.31s	remaining: 26.9s
33:	test: -5.8412743	best: -5.8391073 (30)	total: 5.46s	remaining: 26.7s
34:	test: -5.8416354	best: -5.8391073 (30)	total: 5.62s	remaining: 26.5s
35:	test: -5.8093444	best: -5.8093444 (35)	total: 5.78s	remaining: 26.3s
36:	test: -5.8093444	best: -5.8093444 (35)	total: 5.95s	remaining: 26.2s
37:	test: -5.8094364	best: -5.8093444 (35)	total: 6.11s	remaining: 26s
38:	test: -5.8094289	best: -5.8093444 (35)	total: 6.27s	remaining: 25.9s
39:	test: -5.8094289	best: -5.8093444 (35)	total: 6.43s	remaining: 25.7s
40:	test: -5.8092485	best: -5.8092485 (40)	total: 6.61s	remaining: 25.6s
41:	test: -5.8090530	best: -5.8090530 (41)	total: 6.79s	remaining: 25.6s
42:	test: -5.5811992	best: -5.5811992 (42)	total: 6.98s	remaining: 25.5s
43:	test: -5.5811992	best: -5.5811992 (42)	total: 7.17s	remaining: 25.4s
44:	test: -5.5811992	best: -5.5811992 (42)	total: 7.35s	remaining: 25.3s
45:	test: -5.5534714	best: -5.5534714 (45)	total: 7.53s	remaining: 25.2s
46:	test: -5.5534627	best: -5.5534627 (46)	total: 7.71s	remaining: 25.1s
47:	test: -5.5536438	best: -5.5534627 (46)	total: 7.9s	remaining: 25s
48:	test: -5.7712084	best: -5.5534627 (46)	total: 8.08s	remaining: 24.9s
49:	test: -5.7680398	best: -5.5534627 (46)	total: 8.26s	remaining: 24.8s
50:	test: -5.2549683	best: -5.2549683 (50)	total: 8.45s	remaining: 24.7s
51:	test: -5.2549683	best: -5.2549683 (50)	total: 8.63s	remaining: 24.6s
52:	test: -5.2580736	best: -5.2549683 (50)	total: 8.83s	remaining: 24.5s
53:	test: -5.2581172	best: -5.2549683 (50)	total: 9.01s	remaining: 24.4s
54:	test: -5.2580736	best: -5.2549683 (50)	total: 9.19s	remaining: 24.2s
55:	test: -5.2579212	best: -5.2549683 (50)	total: 9.35s	remaining: 24s
56:	test: -5.5366236	best: -5.2549683 (50)	total: 9.52s	remaining: 23.9s
57:	test: -5.5366222	best: -5.2549683 (50)	total: 9.7s	remaining: 23.7s
58:	test: -5.5366222	best: -5.2549683 (50)	total: 9.87s	remaining: 23.6s
59:	test: -5.5238157	best: -5.2549683 (50)	total: 10.1s	remaining: 23.5s
60:	test: -5.4976930	best: -5.2549683 (50)	total: 10.2s	remaining: 23.3s
61:	test: -5.4976930	best: -5.2549683 (50)	total: 10.4s	remaining: 23.2s
62:	test: -5.4977107	best: -5.2549683 (50)	total: 10.6s	remaining: 23s
63:	test: -5.5032274	best: -5.2549683 (50)	total: 10.7s	remaining: 22.8s
64:	test: -5.5032287	best: -5.2549683 (50)	total: 10.9s	remaining: 22.7s
65:	test: -5.5029756	best: -5.2549683 (50)	total: 11.1s	remaining: 22.5s
66:	test: -5.5029637	best: -5.2549683 (50)	total: 11.3s	remaining: 22.4s
67:	test: -5.5029637	best: -5.2549683 (50)	total: 11.4s	remaining: 22.2s
68:	test: -5.5029637	best: -5.2549683 (50)	total: 11.6s	remaining: 22.1s
69:	test: -5.5032168	best: -5.2549683 (50)	total: 11.8s	remaining: 21.9s
70:	test: -5.5031414	best: -5.2549683 (50)	total: 12s	remaining: 21.8s
71:	test: -5.5127103	best: -5.2549683 (50)	total: 12.2s	remaining: 21.6s
72:	test: -5.2437215	best: -5.2437215 (72)	total: 12.3s	remaining: 21.5s
73:	test: -5.2439528	best: -5.2437215 (72)	total: 12.5s	remaining: 21.3s
74:	test: -5.2439528	best: -5.2437215 (72)	total: 12.7s	remaining: 21.2s
75:	test: -5.2436996	best: -5.2436996 (75)	total: 12.9s	remaining: 21s
76:	test: -5.2434684	best: -5.2434684 (76)	total: 13.1s	remaining: 20.9s
77:	test: -5.2434684	best: -5.2434684 (76)	total: 13.2s	remaining: 20.7s
78:	test: -5.2437429	best: -5.2434684 (76)	total: 13.4s	remaining: 20.5s
79:	test: -5.2434676	best: -5.2434676 (79)	total: 13.6s	remaining: 20.4s
80:	test: -5.2437035	best: -5.2434676 (79)	total: 13.8s	remaining: 20.2s
81:	test: -5.5257902	best: -5.2434676 (79)	total: 13.9s	remaining: 20.1s
82:	test: -5.5251825	best: -5.2434676 (79)	total: 14.1s	remaining: 19.9s
83:	test: -5.5251825	best: -5.2434676 (79)	total: 14.3s	remaining: 19.7s
84:	test: -5.5251604	best: -5.2434676 (79)	total: 14.5s	remaining: 19.6s
85:	test: -5.5257487	best: -5.2434676 (79)	total: 14.6s	remaining: 19.4s
86:	test: -5.5285408	best: -5.2434676 (79)	total: 14.8s	remaining: 19.3s
87:	test: -5.5285408	best: -5.2434676 (79)	total: 15s	remaining: 19.1s
88:	test: -5.5277021	best: -5.2434676 (79)	total: 15.2s	remaining: 19s
89:	test: -5.5277021	best: -5.2434676 (79)	total: 15.4s	remaining: 18.8s
90:	test: -5.5277021	best: -5.2434676 (79)	total: 15.6s	remaining: 18.6s
91:	test: -5.5277021	best: -5.2434676 (79)	total: 15.8s	remaining: 18.5s
92:	test: -5.5276737	best: -5.2434676 (79)	total: 16s	remaining: 18.4s
93:	test: -5.5276737	best: -5.2434676 (79)	total: 16.1s	remaining: 18.2s
94:	test: -5.5276362	best: -5.2434676 (79)	total: 16.3s	remaining: 18.1s
95:	test: -5.5267097	best: -5.2434676 (79)	total: 16.5s	remaining: 17.9s
96:	test: -5.5266178	best: -5.2434676 (79)	total: 16.7s	remaining: 17.7s
97:	test: -5.5259669	best: -5.2434676 (79)	total: 16.9s	remaining: 17.6s
98:	test: -5.5534141	best: -5.2434676 (79)	total: 17.1s	remaining: 17.5s
99:	test: -5.5534141	best: -5.2434676 (79)	total: 17.3s	remaining: 17.3s
100:	test: -5.5534155	best: -5.2434676 (79)	total: 17.5s	remaining: 17.1s
101:	test: -5.5758500	best: -5.2434676 (79)	total: 17.6s	remaining: 17s
102:	test: -5.5758500	best: -5.2434676 (79)	total: 17.8s	remaining: 16.8s
103:	test: -5.5267715	best: -5.2434676 (79)	total: 18s	remaining: 16.6s
104:	test: -5.5267715	best: -5.2434676 (79)	total: 18.2s	remaining: 16.5s
105:	test: -5.5267715	best: -5.2434676 (79)	total: 18.4s	remaining: 16.3s
106:	test: -5.5267715	best: -5.2434676 (79)	total: 18.6s	remaining: 16.2s
107:	test: -5.5535257	best: -5.2434676 (79)	total: 18.8s	remaining: 16s
108:	test: -5.5535257	best: -5.2434676 (79)	total: 18.9s	remaining: 15.8s
109:	test: -5.2715171	best: -5.2434676 (79)	total: 19.1s	remaining: 15.6s
110:	test: -5.2715074	best: -5.2434676 (79)	total: 19.3s	remaining: 15.5s
111:	test: -5.2718975	best: -5.2434676 (79)	total: 19.5s	remaining: 15.3s
112:	test: -5.2718975	best: -5.2434676 (79)	total: 19.7s	remaining: 15.1s
113:	test: -5.2718975	best: -5.2434676 (79)	total: 19.9s	remaining: 15s

114:	test: -5.2718975	best: -5.2434676 (79)	total: 20.1s	remaining: 14.8s
115:	test: -5.2718975	best: -5.2434676 (79)	total: 20.2s	remaining: 14.6s
116:	test: -5.2718864	best: -5.2434676 (79)	total: 20.4s	remaining: 14.5s
117:	test: -5.2715498	best: -5.2434676 (79)	total: 20.6s	remaining: 14.3s
118:	test: -5.2715498	best: -5.2434676 (79)	total: 20.8s	remaining: 14.2s
119:	test: -5.2715498	best: -5.2434676 (79)	total: 21s	remaining: 14s
120:	test: -5.2715498	best: -5.2434676 (79)	total: 21.2s	remaining: 13.8s
121:	test: -5.2946537	best: -5.2434676 (79)	total: 21.3s	remaining: 13.6s
122:	test: -5.2923511	best: -5.2434676 (79)	total: 21.5s	remaining: 13.5s
123:	test: -5.2923511	best: -5.2434676 (79)	total: 21.7s	remaining: 13.3s
124:	test: -5.2923511	best: -5.2434676 (79)	total: 21.9s	remaining: 13.1s
125:	test: -5.2923511	best: -5.2434676 (79)	total: 22.1s	remaining: 13s
126:	test: -5.2923525	best: -5.2434676 (79)	total: 22.3s	remaining: 12.8s
127:	test: -5.2925349	best: -5.2434676 (79)	total: 22.5s	remaining: 12.7s
128:	test: -5.2925349	best: -5.2434676 (79)	total: 22.7s	remaining: 12.5s
129:	test: -5.2925705	best: -5.2434676 (79)	total: 22.8s	remaining: 12.3s
130:	test: -5.2925705	best: -5.2434676 (79)	total: 23s	remaining: 12.1s
131:	test: -5.9039257	best: -5.2434676 (79)	total: 23.2s	remaining: 12s
132:	test: -5.9039257	best: -5.2434676 (79)	total: 23.4s	remaining: 11.8s
133:	test: -5.9039257	best: -5.2434676 (79)	total: 23.5s	remaining: 11.6s
134:	test: -5.9039257	best: -5.2434676 (79)	total: 23.7s	remaining: 11.4s
135:	test: -5.9039257	best: -5.2434676 (79)	total: 23.9s	remaining: 11.3s
136:	test: -5.9039257	best: -5.2434676 (79)	total: 24.1s	remaining: 11.1s
137:	test: -5.9039257	best: -5.2434676 (79)	total: 24.3s	remaining: 10.9s
138:	test: -5.9042686	best: -5.2434676 (79)	total: 24.4s	remaining: 10.7s
139:	test: -5.9042686	best: -5.2434676 (79)	total: 24.6s	remaining: 10.6s
140:	test: -5.9042686	best: -5.2434676 (79)	total: 24.8s	remaining: 10.4s
141:	test: -5.9042686	best: -5.2434676 (79)	total: 25s	remaining: 10.2s
142:	test: -5.9042686	best: -5.2434676 (79)	total: 25.2s	remaining: 10s
143:	test: -5.9042686	best: -5.2434676 (79)	total: 25.3s	remaining: 9.85s
144:	test: -5.9039508	best: -5.2434676 (79)	total: 25.5s	remaining: 9.68s
145:	test: -5.9039508	best: -5.2434676 (79)	total: 25.7s	remaining: 9.51s
146:	test: -5.9039508	best: -5.2434676 (79)	total: 25.9s	remaining: 9.33s
147:	test: -5.9039508	best: -5.2434676 (79)	total: 26.1s	remaining: 9.16s
148:	test: -5.9039466	best: -5.2434676 (79)	total: 26.3s	remaining: 8.99s
149:	test: -5.9062478	best: -5.2434676 (79)	total: 26.4s	remaining: 8.81s
150:	test: -5.9062185	best: -5.2434676 (79)	total: 26.6s	remaining: 8.65s
151:	test: -5.9062185	best: -5.2434676 (79)	total: 26.8s	remaining: 8.47s
152:	test: -5.9061578	best: -5.2434676 (79)	total: 27.1s	remaining: 8.31s
153:	test: -5.9061578	best: -5.2434676 (79)	total: 27.3s	remaining: 8.14s
154:	test: -5.9061578	best: -5.2434676 (79)	total: 27.5s	remaining: 7.97s
155:	test: -5.9061578	best: -5.2434676 (79)	total: 27.7s	remaining: 7.8s
156:	test: -5.9061670	best: -5.2434676 (79)	total: 27.9s	remaining: 7.63s
157:	test: -5.9145848	best: -5.2434676 (79)	total: 28.1s	remaining: 7.46s
158:	test: -5.9145848	best: -5.2434676 (79)	total: 28.2s	remaining: 7.28s
159:	test: -5.9060864	best: -5.2434676 (79)	total: 28.4s	remaining: 7.1s
160:	test: -5.9060864	best: -5.2434676 (79)	total: 28.6s	remaining: 6.93s
161:	test: -5.9145858	best: -5.2434676 (79)	total: 28.8s	remaining: 6.76s
162:	test: -5.9145858	best: -5.2434676 (79)	total: 29s	remaining: 6.58s
163:	test: -5.9144105	best: -5.2434676 (79)	total: 29.2s	remaining: 6.41s
164:	test: -5.9144105	best: -5.2434676 (79)	total: 29.4s	remaining: 6.24s
165:	test: -5.9144105	best: -5.2434676 (79)	total: 29.6s	remaining: 6.07s
166:	test: -5.8544608	best: -5.2434676 (79)	total: 29.9s	remaining: 5.9s
167:	test: -5.8544451	best: -5.2434676 (79)	total: 30.1s	remaining: 5.73s
168:	test: -5.8521101	best: -5.2434676 (79)	total: 30.3s	remaining: 5.55s
169:	test: -5.8521101	best: -5.2434676 (79)	total: 30.5s	remaining: 5.38s
170:	test: -5.8437471	best: -5.2434676 (79)	total: 30.7s	remaining: 5.2s
171:	test: -5.8444083	best: -5.2434676 (79)	total: 30.9s	remaining: 5.03s
172:	test: -5.8444083	best: -5.2434676 (79)	total: 31.1s	remaining: 4.85s
173:	test: -5.8076949	best: -5.2434676 (79)	total: 31.3s	remaining: 4.67s
174:	test: -5.8161204	best: -5.2434676 (79)	total: 31.4s	remaining: 4.49s
175:	test: -5.8161303	best: -5.2434676 (79)	total: 31.6s	remaining: 4.31s
176:	test: -5.8161303	best: -5.2434676 (79)	total: 31.8s	remaining: 4.13s
177:	test: -5.8149095	best: -5.2434676 (79)	total: 32s	remaining: 3.96s
178:	test: -5.8149095	best: -5.2434676 (79)	total: 32.2s	remaining: 3.78s
179:	test: -5.8148989	best: -5.2434676 (79)	total: 32.4s	remaining: 3.6s
180:	test: -5.8148989	best: -5.2434676 (79)	total: 32.6s	remaining: 3.42s
181:	test: -5.8146888	best: -5.2434676 (79)	total: 32.8s	remaining: 3.24s
182:	test: -5.8147830	best: -5.2434676 (79)	total: 33s	remaining: 3.06s
183:	test: -5.8148434	best: -5.2434676 (79)	total: 33.1s	remaining: 2.88s
184:	test: -5.8148434	best: -5.2434676 (79)	total: 33.3s	remaining: 2.7s
185:	test: -5.8146956	best: -5.2434676 (79)	total: 33.5s	remaining: 2.52s
186:	test: -5.8146294	best: -5.2434676 (79)	total: 33.7s	remaining: 2.35s
187:	test: -5.8143885	best: -5.2434676 (79)	total: 33.9s	remaining: 2.17s
188:	test: -5.8144807	best: -5.2434676 (79)	total: 34.1s	remaining: 1.99s
189:	test: -5.8144510	best: -5.2434676 (79)	total: 34.3s	remaining: 1.8s
190:	test: -5.8142009	best: -5.2434676 (79)	total: 34.5s	remaining: 1.62s
191:	test: -5.8031927	best: -5.2434676 (79)	total: 34.7s	remaining: 1.44s
192:	test: -5.8031927	best: -5.2434676 (79)	total: 34.9s	remaining: 1.26s
193:	test: -5.8032552	best: -5.2434676 (79)	total: 35.1s	remaining: 1.08s
194:	test: -5.8032497	best: -5.2434676 (79)	total: 35.3s	remaining: 904ms
195:	test: -5.8036136	best: -5.2434676 (79)	total: 35.4s	remaining: 723ms
196:	test: -5.8036173	best: -5.2434676 (79)	total: 35.6s	remaining: 542ms
197:	test: -5.8036173	best: -5.2434676 (79)	total: 35.8s	remaining: 362ms
198:	test: -5.8036173	best: -5.2434676 (79)	total: 36s	remaining: 181ms
199:	test: -5.8035448	best: -5.2434676 (79)	total: 36.2s	remaining: 0us

bestTest = -5.243467606
bestIteration = 79

Shrink model to first 80 iterations.

In [8]:
pred_score = model.predict(test_data)
pred_score

array([-0.50509083,  0.87444206, -0.63351856, ...,  0.48524673,
       -0.05083283, -0.50704104])

In [9]:
def adopt_label_for_lbg(label):
    if (label == 0) | (label == 4): return 1;
    else: return 0

train_data = train_df.drop(["user_id", "score"], axis=1)
train_label = train_df["score"]
train_group = pd.Series([100] * int(train_data.shape[0]/100))

test_data = test_df.drop(["user_id", "score"], axis=1)
test_label = test_df["score"]
test_group = pd.Series([100] * int(test_data.shape[0]/100))

lgb_train_label = train_label.apply(adopt_label_for_lbg)
lgb_test_label = test_label.apply(adopt_label_for_lbg)

In [10]:
train_data.columns = [str(i) for i in range(len(train_data.columns))]
test_data.columns = [str(i) for i in range(len(test_data.columns))]

In [11]:
train_data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
116375,0,2,785,26,6,1,8,3,0,1,75,1,0,5,1.581081,1.081081,1.090909,0.08
45075,0,2,785,26,6,1,8,3,0,1,29,0,1,11,3.730548,1.456772,1.020000,0.40
128775,0,2,785,26,6,1,8,3,0,1,83,1,1,10,2.800000,0.660000,1.000000,0.04
46625,0,2,785,26,6,1,8,3,0,1,30,1,0,5,2.331897,1.150862,1.018182,0.40
113275,0,2,785,26,6,1,8,3,0,1,73,1,0,0,0.962406,1.624060,1.625000,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66378,0,1,307,9,3,0,9,3,0,0,42,1,0,7,2.246973,0.871671,1.400379,0.24
94278,0,1,307,9,3,0,9,3,0,0,60,0,1,11,2.821918,1.214612,1.000000,0.12
112878,0,1,307,9,3,0,9,3,0,0,72,0,0,7,1.869822,1.017751,1.250000,0.08
18328,0,1,307,9,3,0,9,3,0,0,11,1,0,2,2.990932,1.700742,2.261244,0.76
22978,0,1,307,9,3,0,9,3,0,0,14,1,0,4,2.526978,1.089029,3.646402,0.64

In [12]:
uncategorical_feature = [2, 14, 15, 16, 17]
categorical_feature = [i for i in range(18) if not i in uncategorical_feature]
categorical_feature

[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [13]:
lgb_train = lgb.Dataset(train_data, label = lgb_train_label, weight = train_label, group=train_group)
lgb_vaid =  lgb.Dataset(test_data, label = lgb_test_label, weight = test_label, group=test_group)

max_position = 20
lgbm_params =  {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'lambdarank',
    'metric': 'ndcg',   # for lambdarank
    'ndcg_eval_at': [1,2,3],  # for lambdarank
    'max_position': max_position,  # for lambdarank
    'learning_rate': 1e-8,
    'min_data': 1,
    'min_data_in_bin': 1,
}

uncategorical_feature = [2, 14, 15, 16, 17]
lgb_clf = lgb.train(
    lgbm_params,
    lgb_train,
    categorical_feature= [i for i in range(18) if not i in uncategorical_feature],
    num_boost_round=10,
    valid_sets=[lgb_train, lgb_vaid],
    valid_names=['train','valid'],
    early_stopping_rounds=2,
    verbose_eval=1
)

/Users/nobuyuki.ishida/.pyenv/versions/3.7.5/lib/python3.7/site-packages/lightgbm/basic.py:1295: UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  'New categorical_feature is {}'.format(sorted(list(categorical_feature))))

[1]	train's ndcg@1: -0.0278138	train's ndcg@2: -0.0295361	train's ndcg@3: -0.0291329	valid's ndcg@1: -0.0356864	valid's ndcg@2: -0.0335922	valid's ndcg@3: -0.0345292
Training until validation scores don't improve for 2 rounds
[2]	train's ndcg@1: -0.0296337	train's ndcg@2: -0.0307396	train's ndcg@3: -0.0307239	valid's ndcg@1: -0.044175	valid's ndcg@2: -0.0397854	valid's ndcg@3: -0.03797
[3]	train's ndcg@1: -0.0308059	train's ndcg@2: -0.0309889	train's ndcg@3: -0.0306671	valid's ndcg@1: -0.038155	valid's ndcg@2: -0.0396294	valid's ndcg@3: -0.0374543
Early stopping, best iteration is:
[1]	train's ndcg@1: -0.0278138	train's ndcg@2: -0.0295361	train's ndcg@3: -0.0291329	valid's ndcg@1: -0.0356864	valid's ndcg@2: -0.0335922	valid's ndcg@3: -0.0345292